bot_name: nootifications-bot

clients:
  kraken:
    smoothing: 0.9
    throttle_seconds: 10.0
    reconnect_delay: 5
    max_reconnect_attempts: 10
  alpaca:
    feed: iex
    smoothing: 0.9
    throttle_seconds: 10.0
    reconnect_delay: 5
    max_reconnect_attempts: 10

assets:
  - name: ETH
    client: kraken
    ticker: ETH/USD
    delta: 0.01

  - name: BTC
    client: kraken
    ticker: BTC/USD
    delta: 1000

  # - name: Apple
  #   client: alpaca
  #   ticker: AAPL
  #   delta: 0.1
