bot_name: nootifications-bot

clients:
  kraken:
    smoothing: 0.9
    throttle_seconds: 10.0
    reconnect_delay: 5
    max_reconnect_attempts: 10
    stale_timeout_seconds: 600
  alpaca:
    feed: iex
    smoothing: 0.5
    throttle_seconds: 10.0
    reconnect_delay: 5
    max_reconnect_attempts: 10
    stale_timeout_seconds: 600

assets:
  - name: ETH
    client: kraken
    ticker: ETH/USD
    percent: 0.01

  - name: BTC
    client: kraken
    ticker: BTC/USD
    interval: 1000

  - name: Apple
    client: alpaca
    ticker: AAPL
    target: 250
